#!/usr/bin/env node
var argv = require('yargs')
  .option('init', {
    alias : 'init',
    demand: true,
    default: 'init',
    describe: 'init your smart contract',
    type: 'string'
  })
  .option('deploy', {
    alias : 'deploy',
    demand: true,
    default: 'init',
    describe: 'deploy your smart contract',
    type: 'string'
  })
  .option('compile', {
    alias : 'compile',
    demand: true,
    default: 'init',
    describe: 'compile your smart contract',
    type: 'string'
  })
  .usage('Usage: conflux-truffle [options]')
  .example('conflux-truffle init', '"init your smart contract"')
  .help('h')
  .alias('h', 'help')
  .epilog('copyright conflux-chain')
  .argv;

console.log('conflux-truffle ', argv._);
